---
- name: gitsync
  hosts: srvthc
  become: true
  tasks:
    - name: pull from git
      git:
        repo: git@github.com:thcoppens/dotfiles_srv.git
        dest: /home/thc/dotfiles_srv
        update: yes
        version: main
